/**
 * Feature 004 Phase 3 — Structured policy engine with risk-tier routing.
 * Replaces regex-on-JSON.stringify pattern in 004 workflow path.
 *
 * [SPEC]
 * - evaluate(StructuredContentPiece) → PolicyResult with riskTier
 * - action=block → CRITICAL; max severity maps to HIGH/MED; none → LOW
 * - Approval routing uses riskTier ONLY (confidence is auxiliary)
 */

import type { CreatedContent } from '@/lib/ai-cmo/creator-agent';
import type { StrategicPlan } from '@/lib/ai-cmo/strategic-brain';
import type {
  PolicyResult,
  PolicySeverity,
  PolicyViolation,
  RiskTier,
  StructuredContentPiece,
  StructuredPolicyRule,
} from '@/lib/governance/types/policy';

export const POLICY_RULES_V2: StructuredPolicyRule[] = [
  {
    id: 'competitor-pricing',
    name: 'Competitor Pricing Claims',
    condition: (c) => c.mentionsCompetitor && c.containsPricingData,
    action: 'require_approval',
    severity: 'critical',
    reason: 'Pricing claims require legal verification',
  },
  {
    id: 'legal-claims',
    name: 'Legal/Regulatory Claims',
    condition: (c) => c.containsLegalLanguage || c.containsComplianceTerms,
    action: 'require_approval',
    severity: 'critical',
    reason: 'Legal claims require counsel review',
  },
  {
    id: 'government-sector',
    name: 'Government Sector Content',
    condition: (c) => c.targetsGovernmentSegment,
    action: 'require_approval',
    severity: 'high',
    reason: 'Government content has strict compliance requirements',
  },
  {
    id: 'religious-political',
    name: 'Religious/Political Topics',
    condition: (c) => c.containsReligiousOrPoliticalContent,
    action: 'block',
    severity: 'critical',
    reason: 'Brand safety: avoid religious/political topics entirely',
  },
  {
    id: 'arabic-dialect-accuracy',
    name: 'Arabic Dialect Accuracy',
    condition: (c) => c.locale.startsWith('ar-') && (c.confidence ?? 1) < 0.9,
    action: 'require_approval',
    severity: 'high',
    reason: 'Arabic dialect errors can damage brand in MENA',
  },
  {
    id: 'healthcare-financial',
    name: 'Healthcare/Financial Services',
    condition: (c) => c.industry === 'healthcare' || c.industry === 'financial',
    action: 'require_approval',
    severity: 'high',
    reason: 'Regulated industries require compliance review',
  },
];

export const MENA_PDPL_RULES: StructuredPolicyRule[] = [
  {
    id: 'mena-pdpl-processing',
    name: 'MENA PDPL — Personal Data Processing',
    condition: (c) => /processing data|personal data|data subject/i.test(c.text),
    action: 'require_approval',
    severity: 'high',
    reason: 'MENA PDPL requires explicit consent language for personal data processing',
  },
  {
    id: 'mena-pdpl-cross-border',
    name: 'MENA PDPL — Cross-Border Transfer',
    condition: (c) => /cross-border|cross border|data transfer/i.test(c.text),
    action: 'require_approval',
    severity: 'critical',
    reason: 'Cross-border data transfer requires PDPL adequacy assessment',
  },
];

export const EU_AI_ACT_RULES: StructuredPolicyRule[] = [
  {
    id: 'eu-ai-act-disclosure',
    name: 'EU AI Act — Undisclosed AI Content',
    condition: (c) => /undisclosed ai|ai-generated|generated by ai/i.test(c.text) && !/disclosed|labeled/i.test(c.text),
    action: 'require_approval',
    severity: 'high',
    reason: 'EU AI Act requires disclosure of AI-generated marketing content',
  },
];

export type BrandPolicyContext = {
  dataRegion?: string;
};

export type { StructuredContentPiece, PolicyResult, PolicyViolation, RiskTier };

const SEVERITY_ORDER: PolicySeverity[] = ['low', 'medium', 'high', 'critical'];

function toViolation(rule: StructuredPolicyRule): PolicyViolation {
  return {
    id: rule.id,
    name: rule.name,
    action: rule.action,
    severity: rule.severity,
    reason: rule.reason,
  };
}

function severityToRiskTier(severity: PolicySeverity): RiskTier {
  switch (severity) {
    case 'critical':
      return 'CRITICAL';
    case 'high':
      return 'HIGH';
    case 'medium':
      return 'MED';
    default:
      return 'LOW';
  }
}

function maxSeverity(violations: PolicyViolation[]): PolicySeverity | null {
  if (!violations.length) return null;
  return violations.reduce<PolicySeverity>(
    (max, v) =>
      SEVERITY_ORDER.indexOf(v.severity) > SEVERITY_ORDER.indexOf(max) ? v.severity : max,
    violations[0]!.severity,
  );
}

function assignRiskTier(violations: PolicyViolation[]): RiskTier {
  if (violations.some((v) => v.action === 'block')) {
    return 'CRITICAL';
  }

  const max = maxSeverity(violations);
  if (!max) return 'LOW';
  return severityToRiskTier(max);
}

export class PolicyEngineV2 {
  constructor(private readonly rules: StructuredPolicyRule[] = POLICY_RULES_V2) {}

  evaluate(content: StructuredContentPiece, brand?: BrandPolicyContext): PolicyResult {
    let activeRules = this.rules;

    const region = brand?.dataRegion?.toLowerCase();
    if (region === 'mena' || region === 'uae' || region === 'sa') {
      activeRules = [...activeRules, ...MENA_PDPL_RULES];
    }
    if (region === 'eu' || region === 'eea') {
      activeRules = [...activeRules, ...EU_AI_ACT_RULES];
    }

    const violations = activeRules.filter((rule) => rule.condition(content)).map(toViolation);
    const riskTier = assignRiskTier(violations);

    if (violations.some((v) => v.action === 'block')) {
      return {
        approved: false,
        riskTier: 'CRITICAL',
        reason: 'Critical policy violation — content blocked',
        violations,
        requiresApproval: true,
      };
    }

    if (violations.some((v) => v.action === 'require_approval')) {
      return {
        approved: false,
        riskTier,
        reason: 'Requires human approval per risk tier',
        violations,
        requiresApproval: true,
      };
    }

    if (violations.some((v) => v.action === 'flag')) {
      return {
        approved: true,
        riskTier: riskTier === 'LOW' ? 'MED' : riskTier,
        reason: 'Flagged for review — auto-publish allowed at LOW/MED',
        violations,
        requiresApproval: false,
      };
    }

    return {
      approved: true,
      riskTier: 'LOW',
      reason: 'Approved',
      violations: [],
      requiresApproval: false,
    };
  }
}

type ComplianceFlags = Partial<{
  mentionsCompetitor: boolean;
  containsPricingData: boolean;
  containsLegalLanguage: boolean;
  containsComplianceTerms: boolean;
  targetsGovernmentSegment: boolean;
  containsReligiousOrPoliticalContent: boolean;
  industry: string;
}>;

function readComplianceFlags(source: Record<string, unknown> | undefined): ComplianceFlags {
  const compliance = source?.compliance;
  if (!compliance || typeof compliance !== 'object') {
    return {};
  }
  return compliance as ComplianceFlags;
}

function includesAny(haystack: string, needles: string[]): boolean {
  const lower = haystack.toLowerCase();
  return needles.some((needle) => lower.includes(needle));
}

function inferFlagsFromText(text: string): ComplianceFlags {
  return {
    mentionsCompetitor: includesAny(text, ['competitor', 'rival', 'versus', ' vs ']),
    containsPricingData: includesAny(text, ['$', 'price', 'pricing', 'cost', 'fee']),
    containsLegalLanguage: includesAny(text, ['guarantee', 'warranty', 'legal', 'lawsuit']),
    containsComplianceTerms: includesAny(text, ['compliance', 'regulation', 'pdpl', 'gdpr']),
    targetsGovernmentSegment: includesAny(text, ['government', 'public sector', 'ministry']),
    containsReligiousOrPoliticalContent: includesAny(text, [
      'religion',
      'political',
      'election',
      'vote for',
    ]),
  };
}

/** Build structured ContentPiece from Creator output — never serializes plan wrapper. */
export function contentPieceFromPlanAndContent(input: {
  plan: StrategicPlan;
  content: CreatedContent;
  locale: string;
  industry?: string;
  qualityScore?: number;
}): StructuredContentPiece {
  const metadataFlags = readComplianceFlags(input.content.draftMetadata);
  const planText = [input.plan.objective, ...input.plan.keyMessages].join(' ');
  const contentText = [input.content.caption, input.content.callToAction].join(' ');
  const combinedText = `${planText} ${contentText}`;
  const inferred = inferFlagsFromText(combinedText);

  return {
    text: contentText,
    locale: input.locale,
    industry: metadataFlags.industry ?? input.industry ?? input.content.draftMetadata.industry as string | undefined,
    mentionsCompetitor: metadataFlags.mentionsCompetitor ?? inferred.mentionsCompetitor ?? false,
    containsPricingData: metadataFlags.containsPricingData ?? inferred.containsPricingData ?? false,
    containsLegalLanguage: metadataFlags.containsLegalLanguage ?? inferred.containsLegalLanguage ?? false,
    containsComplianceTerms: metadataFlags.containsComplianceTerms ?? inferred.containsComplianceTerms ?? false,
    targetsGovernmentSegment:
      metadataFlags.targetsGovernmentSegment ?? inferred.targetsGovernmentSegment ?? false,
    containsReligiousOrPoliticalContent:
      metadataFlags.containsReligiousOrPoliticalContent ??
      inferred.containsReligiousOrPoliticalContent ??
      false,
    confidence: input.qualityScore,
  };
}

/** Structured plan-only review (objective/keyMessages fields — no JSON.stringify). */
export function contentPieceFromPlan(input: {
  plan: StrategicPlan;
  locale: string;
  industry?: string;
}): StructuredContentPiece {
  const planText = [input.plan.objective, ...input.plan.keyMessages].join(' ');
  const inferred = inferFlagsFromText(planText);

  return {
    text: planText,
    locale: input.locale,
    industry: input.industry,
    mentionsCompetitor: inferred.mentionsCompetitor ?? false,
    containsPricingData: inferred.containsPricingData ?? false,
    containsLegalLanguage: inferred.containsLegalLanguage ?? false,
    containsComplianceTerms: inferred.containsComplianceTerms ?? false,
    targetsGovernmentSegment: inferred.targetsGovernmentSegment ?? false,
    containsReligiousOrPoliticalContent: inferred.containsReligiousOrPoliticalContent ?? false,
  };
}

export const policyEngineV2 = new PolicyEngineV2();

export const policyEngineV2Utils = {
  PolicyEngineV2,
  policyEngineV2,
  POLICY_RULES_V2,
  contentPieceFromPlanAndContent,
  contentPieceFromPlan,
};
