/**
 * Ensure a workspace API key exists for UAT / live integration tests.
 * Writes raw key to .uat-secrets.local (gitignored) when a new key is created.
 *
 * Usage: npx tsx scripts/ensure-uat-api-key.ts [--workspace-id <uuid>]
 */
import { createHash, randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const root = join(scriptDir, '..');
const SECRETS_FILE = join(root, '.uat-secrets.local');
const DEFAULT_WORKSPACE = '11111111-1111-1111-1111-111111111111';

function loadEnv() {
  for (const file of ['.env', '.env.local']) {
    const p = join(root, file);
    if (!existsSync(p)) continue;
    for (const line of readFileSync(p, 'utf8').split('\n')) {
      const t = line.trim();
      if (!t || t.startsWith('#')) continue;
      const eq = t.indexOf('=');
      if (eq <= 0) continue;
      process.env[t.slice(0, eq).trim()] = t.slice(eq + 1).trim().replace(/^['"]|['"]$/g, '');
    }
  }
}

function parseWorkspaceId(): string {
  const idx = process.argv.indexOf('--workspace-id');
  if (idx >= 0 && process.argv[idx + 1]) return process.argv[idx + 1]!;
  return process.env.NEXT_PUBLIC_DEFAULT_WORKSPACE_ID ?? DEFAULT_WORKSPACE;
}

function readSecretsFile(): Record<string, string> {
  if (!existsSync(SECRETS_FILE)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(SECRETS_FILE, 'utf8').split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq <= 0) continue;
    out[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return out;
}

async function main() {
  loadEnv();
  const workspaceId = parseWorkspaceId();
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
    process.exit(1);
  }

  const existingEnv = process.env.NEXUS_API_KEY?.trim();
  if (existingEnv) {
    console.log('NEXUS_API_KEY already set in environment');
    process.exit(0);
  }

  const secrets = readSecretsFile();
  const savedKey = secrets.NEXUS_API_KEY?.trim();
  if (savedKey) {
    const hash = createHash('sha256').update(savedKey).digest('hex');
    const supabase = createClient(url, serviceKey, { auth: { persistSession: false } });
    const { data } = await supabase.from('api_keys').select('id').eq('key_hash', hash).maybeSingle();
    if (data?.id) {
      console.log(`Using saved key from .uat-secrets.local (workspace ${workspaceId})`);
      console.log(`NEXUS_API_KEY=${savedKey}`);
      process.exit(0);
    }
  }

  const rawKey = `nsk_live_${randomBytes(24).toString('hex')}`;
  const keyHash = createHash('sha256').update(rawKey).digest('hex');
  const supabase = createClient(url, serviceKey, { auth: { persistSession: false } });

  const { error } = await supabase.from('api_keys').insert({
    workspace_id: workspaceId,
    name: 'human-uat-key',
    key_hash: keyHash,
    scopes: ['read:posts', 'write:posts'],
  });

  if (error) {
    console.error('Failed to insert api_keys row:', error.message);
    process.exit(1);
  }

  const header = existsSync(SECRETS_FILE)
    ? ''
    : '# UAT secrets - DO NOT COMMIT\n# Generated by scripts/ensure-uat-api-key.ts\n';
  if (header) writeFileSync(SECRETS_FILE, header, 'utf8');
  appendFileSync(SECRETS_FILE, `NEXUS_API_KEY=${rawKey}\nWORKSPACE_ID=${workspaceId}\n`, 'utf8');

  console.log('Created new UAT API key (saved to .uat-secrets.local)');
  console.log(`NEXUS_API_KEY=${rawKey}`);
  console.log(`WORKSPACE_ID=${workspaceId}`);
}

main();
